収支情報一覧を取得するメソッドを作成する
Ryoma137/okozukai pull request #27
Opened 2022-06-24 06:38 UTC by Ryoma137

AccountBookService に、AccountRepository を利用して Account の一覧を取得するメソッドを作成する

2022-06-24 08:04 UTC, t-ita requested changes
@Ryoma137 テストデータに不足があるため、メソッド仕様のチェックが不十分で、仕様を満たせていません。
正しいテストに修正して、不具合を見つけてください。

2022-06-24 08:04 UTC, t-ita commented on src/test/java/com/example/okozukai/service/AccountBookServiceTest.java
> +        actual.sort(Comparator.comparing(Account::getItemDate).reversed());
`actual` はテスト対象メソッドの結果なので、これを変更するのはユニットテストとしては問題があります。
変更されていない `actual` の要素を直接確認するようにしてください

2022-06-24 08:04 UTC, t-ita commented on src/test/java/com/example/okozukai/service/AccountBookServiceTest.java
> +    @Sql("/test-schema.sql")
仕様をチェックするための テストデータが不十分なので、仕様の不足に気づいていないです。
何が不足しているかは、テストで確認しましょう（それがテストの目的なので）

一覧取得の仕様は、
> 登録された収支一覧を日付の降順（日付が重なる場合は登録順）で表示する
です。

これに必要なテストデータは、今の `test-schema.sql` に記載されている3件では不十分です。

2022-06-27 09:52 UTC, t-ita requested changes
まだ、仕様が満たせていないので、確認をお願いします。

2022-06-27 09:52 UTC, t-ita commented on src/main/java/com/example/okozukai/service/AccountBookService.java
> +        dataFromDB.sort(Comparator.comparing(Account::getItemDate).reversed());
> dataFromDB.sort(Comparator.comparing(Account::getItemDate).reversed());

この場合、日付だけでソートしていますが、仕様は、
`登録された収支一覧を日付の降順（日付が重なる場合は登録順）で表示する` 
なので、まだ満たせていません。
登録順でもソートするようにしてください。

（ヒント：この実装についてテストする場合は、テストテーブル生成時に自動ID生成をオフにしたうえで、ID を直接指定してレコードを生成することで、テストすることができます）

2022-06-30 05:29 UTC, Ryoma137 commented on src/main/java/com/example/okozukai/service/AccountBookService.java
> +        dataFromDB.sort(Comparator.comparing(Account::getItemDate).reversed());
確実に指定したIDが各レコードに付与されるために、IDを自動生成ではなく手動で直接指定したsqlファイルを作成。
`getFindAll` で取得できた値が本当に`登録された収支一覧を日付の降順（日付が重なる場合は登録順）で表示`されているかを確認するために、`getFindAll`で取得したリストの要素をデータを日付の降順（日付が重なる場合は登録の降順）で一つずつ指定し、期待値の値が各リストの要素に入っているかを確認する。
（`getFindAll`でデータを取得した時点で、データの順番はデータを日付の降順（日付が重なる場合は登録の降順)になっているはず。)

2022-06-30 06:12 UTC, Ryoma137 commented
`登録された収支一覧を日付の降順（日付が重なる場合は登録順）で表示する`の実装とテストを追加しました。

2022-06-30 07:52 UTC, t-ita approved these changes
OK です！

2022-06-30 08:03 UTC, merged