Create account repository
Ryoma137/okozukai pull request #5
Opened 2022-06-17 07:09 UTC by Ryoma137

- AccountRepository インターフェースが存在すること
- AccountRepository インターフェースは CRUDRepository を継承していること
- AccountRepository の JUnit テストが存在すること

2022-06-17 08:16 UTC, t-ita requested changes
@Ryoma137 JUnit のテストはプログラムの仕様をテスト・確認するものです。それを意識すると、テストの書き方が変わると思います。

2022-06-17 08:16 UTC, t-ita commented on src/main/java/com/example/okozukai/entity/Account.java
> +import com.sun.istack.NotNull;
不要な import が復活しちゃいましたね

2022-06-17 08:16 UTC, t-ita commented on src/main/java/com/example/okozukai/repository/AccountRepository.java
> +public interface AccountRepository extends JpaRepository<Account, Integer> {
JpaRepository を継承したのは何故ですか？（明確な意志があれば変更の必要は無いです）

2022-06-17 08:16 UTC, t-ita commented on src/main/java/com/example/okozukai/repository/AccountRepository.java
> +public interface AccountRepository extends JpaRepository<Account, Integer> {
もう一点。Account の id は Integer 型じゃないですよね？

2022-06-17 08:16 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +    @DisplayName("IDがNullの時に@IDがNullの時に@GeneratedValueでIDが正しく生成されること")
DisplayName に各日本語は、「何をテストしているのか」をレビュアーに伝える材料の一つです。
ちょっと冷静になって、（誤解が発生しないように）明確な日本語で書きましょう

2022-06-17 08:16 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(3).getId(), "与えられたデータがDBのID列の最後尾に追加されていることを確認");
findAll() の結果は、データベースの実装によりますが登録順で返ってくるとは限らないので、`get(3)` と決め打ちするのは危険です。
また、データベースは単なるデータの容れ物なので、「最後尾」であることをテストする必要はないのでは、と考えます。
この場合は、「追加」された事実だけをテストすればいいのではないでしょうか？
そのテストをするのに、`get(3)` は適切でしょうか？

2022-06-17 08:16 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(3).getId(), "与えられたデータのキーが一致するデータがDBに存在しない時、与えられたデータでDBの更新ではなく、与えられたデータのキーで新たなデータが登録されているかの確認");
この assertion が、メッセージに記載されている
> 与えられたデータのキーが一致するデータがDBに存在しない時、与えられたデータでDBの更新ではなく、与えられたデータのキーで新たなデータが登録されているかの確認
この文章と合っていません。

2022-06-17 11:17 UTC, Ryoma137 commented on src/main/java/com/example/okozukai/repository/AccountRepository.java
> +public interface AccountRepository extends JpaRepository<Account, Integer> {
crudRepositoryを継承すると、findAllでDBから値を取得する際List型ではなく、Iterable型で取得されるので、JpaRepositoryを継承しています。

2022-06-17 11:41 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(3).getId(), "与えられたデータがDBのID列の最後尾に追加されていることを確認");
登録順を期待値で予測するテストを削除し、データが与えられる前と後のDBに保存されているデータ数の確認テストのみに変更しました。

2022-06-17 11:42 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +    @DisplayName("IDがNullの時に@IDがNullの時に@GeneratedValueでIDが正しく生成されること")
二重になっていた`IDがNullの時に`を削除し、正しい日本語に直しました。

2022-06-17 11:43 UTC, Ryoma137 commented on src/main/java/com/example/okozukai/repository/AccountRepository.java
> +public interface AccountRepository extends JpaRepository<Account, Integer> {
AccountのIDは`Long`型なので、`JpaRepository<Account, Long>`に変更しました

2022-06-17 11:45 UTC, Ryoma137 commented
レビューでの指摘点を修正したので、ご確認お願いします。

2022-06-20 00:56 UTC, t-ita commented on src/main/java/com/example/okozukai/repository/AccountRepository.java
> +public interface AccountRepository extends JpaRepository<Account, Integer> {
OKです。

2022-06-20 01:33 UTC, t-ita commented on src/main/java/com/example/okozukai/entity/Account.java
> +import com.sun.istack.NotNull;
消去されていることを確認しました。

2022-06-20 01:33 UTC, t-ita commented on src/main/java/com/example/okozukai/repository/AccountRepository.java
> +public interface AccountRepository extends JpaRepository<Account, Integer> {
修正を確認しました。

2022-06-20 01:35 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +    @DisplayName("IDがNullの時に@IDがNullの時に@GeneratedValueでIDが正しく生成されること")
修正を確認しました。

2022-06-20 01:43 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(3).getId(), "与えられたデータがDBのID列の最後尾に追加されていることを確認");
修正は確認できましたが、まだ問題があように感じるので、Review で指摘します。

2022-06-20 01:43 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(3).getId(), "与えられたデータのキーが一致するデータがDBに存在しない時、与えられたデータでDBの更新ではなく、与えられたデータのキーで新たなデータが登録されているかの確認");
変更されたようですが、まだ問題があるように感じるので、Review で指摘します。

2022-06-20 02:08 UTC, t-ita requested changes
テストケースについて指摘しています。
テストケースの Assert に必要なデータの取り方がわからない場合は質問してください。

2022-06-20 02:08 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertEquals(4, actual.size(), "データを与えた後のDBに保存されているデータ数を確認");
追加のテストについては上と同じです。
また、DisplayName に書かれている「DBが更新されずに」の部分がテストされていないですね。

2022-06-20 05:31 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertEquals(4, actual.size(), "データを与えた後のDBに保存されているデータ数を確認");
上記と同様、件数だけでなく、実際に追加されたデータが存在するかの確認テストを追加しました。

2022-06-20 05:31 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertEquals(1, actual.size(), "データを与えた後のDBに保存されているデータ数を確認");
件数だけでなく、実際に追加されたデータが存在するかの確認テストを追加しました。

2022-06-20 05:35 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertEquals(4, actual.size(), "データを与えた後のDBに保存されているデータ数を確認");
以下の2点のテスト観点を追加しました。
追加される = 更新されないなので、 以下のテスト観点で「DBが更新されずに」の部分もテストされていると思っています。

* データを与える前にsqlで追加したデータ数分のID列が既に使用されているかの確認テストの追加
* データを与えた後にデータが新規に保存され、追加されているかの確認テストの追加

2022-06-20 07:14 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertEquals(1, actual.size(), "データを与えた後のDBに保存されているデータ数を確認");
追加された内容が不十分であると感じるので、レビューにて指摘します。

2022-06-20 07:14 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertEquals(4, actual.size(), "データを与えた後のDBに保存されているデータ数を確認");
追加された内容が不十分であると感じるので、レビューにて指摘します。

2022-06-20 07:15 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertEquals(4, actual.size(), "データを与えた後のDBに保存されているデータ数を確認");
追加された内容が不十分であると感じるので、レビューにて指摘します。

2022-06-20 07:32 UTC, t-ita requested changes
タスク一覧から読み取れる、今回のテストは

- Account が登録されること

のテストです。

これを確認するためには、`CRUDRepository` の `save()` メソッドで登録処理が実行される以下の仕様について確認する必要があります。（`save()` の仕様はドキュメントを見て確認します。自分が作ったメソッドじゃないですからね）

- ID が null の状態で Entity を save に渡すと `INSERT` が実行される（この場合、ID が自動的に付与される）
- `INSERT` 処理によって、Entity のフィールドに対応するテーブルカラムに、Entity のデータが格納されていること

上記の様に、仕様から確認事項を考える必要があります。
この観点でいくと、今の確認事項（テストケース）は不十分です。

2022-06-20 07:32 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(0), "与えられたデータが存在することの確認");
このテストでは、 repositoryから全件取得されたリストの index=0 にデータが「存在すること」は確認できますが、こちらが指定したデータが、期待した仕様に従って格納されていることは確認できません。
面倒かも知れませんが、登録元のオブジェクトと、DBから取得したオブジェクトの各フィールドが一致していることを確認してください。

2022-06-20 07:32 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(3), "与えられたデータが存在する事を確認");
上に同じ

2022-06-20 07:32 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(3).getId(),"データを与えた後にID列の4番目にデータが保存されている事を確認");
前にも指摘していますが、findAll はソート順を確定出来ないので、index を直接指定することはできません。
そのため、 `get(3)` のような形で index を直接指定するやり方は不適切です。
では、データが順不同で並んでいる（かも知れないが）、ID が自動付与されている状態で、一番最後に追加されたデータを取得するには、どのような手続きを踏めば取得出来ると思いますか？（論理パズル的な質問です）

2022-06-20 07:44 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(3).getId(),"データを与えた後にID列の4番目にデータが保存されている事を確認");
もう一点、指摘を忘れていました。

> 追加される = 更新されないなので、 以下のテスト観点の追加により「DBが更新されずに」の部分もテストされていると思っています。
> - データを与える前にsqlで追加したデータ数分のID列が既に使用されているかの確認テストの追加
> - データを与えた後にデータが新規に保存され、追加されているかの確認テストの追加

上記テストでは、「更新されない」ことは担保されないですね。（もしかしたら、登録時に他のデータを削除しているかもしれない）
なので、追加前のデータがそのまま存在している事を確認する必要があります。

2022-06-20 08:36 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(3).getId(),"データを与えた後にID列の4番目にデータが保存されている事を確認");
`assertNotNull(actual.get(3).getId(),"データを与えた後にID列の4番目にデータが保存されている事を確認");` を    `assertNotNull(actual.get(3),"追加されたデータが存在する");`に変更して、データが追加されているかどうかを確認しても`get(3)`で直接indexを指定しているので変わらないですよね...
考えたものの、正直解答に全く導けそうにないので、何かしらをヒントをいただくことはできないでしょうか？

> 前にも指摘していますが、findAll はソート順を確定出来ないので、index を直接指定することはできません。 そのため、 `get(3)` のような形で index を直接指定するやり方は不適切です。 では、データが順不同で並んでいる（かも知れないが）、ID が自動付与されている状態で、一番最後に追加されたデータを取得するには、どのような手続きを踏めば取得出来ると思いますか？（論理パズル的な質問です）

2022-06-20 08:38 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(3).getId(),"データを与えた後にID列の4番目にデータが保存されている事を確認");
こちらもfindAllでデータを取得しているので、`get()`でindexを指定する方法が使えないとなると、追加前のデータがそのまま存在している事を確認する方法がわからないのでヒントをいただけたら幸いです。

> もう一点、指摘を忘れていました。
> 
> > 追加される = 更新されないなので、 以下のテスト観点の追加により「DBが更新されずに」の部分もテストされていると思っています。
> > 
> > * データを与える前にsqlで追加したデータ数分のID列が既に使用されているかの確認テストの追加
> > * データを与えた後にデータが新規に保存され、追加されているかの確認テストの追加
> 
> 上記テストでは、「更新されない」ことは担保されないですね。（もしかしたら、登録時に他のデータを削除しているかもしれない） なので、追加前のデータがそのまま存在している事を確認する必要があります。

2022-06-20 09:14 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(3).getId(),"データを与えた後にID列の4番目にデータが保存されている事を確認");
@Ryoma137 ヒントではなく直接的な内容になりますが、追加したデータを私が取得するとしたら、
ID が自動付与されている
-> 最後に追加されたレコードの ID は、すべてのレコードの ID の中で最大のはず
-> `findAll()` でテーブルの内容を全件取得して、ID が最大になっているレコードを取得する
という方法をとります
（ほかにもいくつか方法は考えられますが、いまある材料ならこの辺りが妥当かと）

2022-06-20 15:03 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(3).getId(),"データを与えた後にID列の4番目にデータが保存されている事を確認");
板垣さんのコメントを参考にstreamでIDの最大値を取得し、その最大値のIDがNullではない事を確認するテストに変更しました。

> @Ryoma137 ヒントではなく直接的な内容になりますが、追加したデータを私が取得するとしたら、 ID が自動付与されている -> 最後に追加されたレコードの ID は、すべてのレコードの ID の中で最大のはず -> `findAll()` でテーブルの内容を全件取得して、ID が最大になっているレコードを取得する という方法をとります （ほかにもいくつか方法は考えられますが、いまある材料ならこの辺りが妥当かと）

> `assertNotNull(actual.get(3).getId(),"データを与えた後にID列の4番目にデータが保存されている事を確認");` を `assertNotNull(actual.get(3),"追加されたデータが存在する");`に変更して、データが追加されているかどうかを確認しても`get(3)`で直接indexを指定しているので変わらないですよね... 考えたものの、正直解答に導けそうにないので、何かしらをヒントをいただくことはできないでしょうか？
> 
> > 前にも指摘していますが、findAll はソート順を確定出来ないので、index を直接指定することはできません。 そのため、 `get(3)` のような形で index を直接指定するやり方は不適切です。 では、データが順不同で並んでいる（かも知れないが）、ID が自動付与されている状態で、一番最後に追加されたデータを取得するには、どのような手続きを踏めば取得出来ると思いますか？（論理パズル的な質問です）

2022-06-20 16:43 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(3).getId(),"データを与えた後にID列の4番目にデータが保存されている事を確認");
anyMatchでDBからデータを取得後のデータにDBからデータを取得前のデータが含まれているかを確認するテストに変更しました。

> こちらもfindAllでデータを取得しているので、`get()`でindexを指定する事は不適切となると、追加前のデータがそのまま存在している事を確認する方法がわからないのでヒントをいただけたら幸いです。
> 
> > もう一点、指摘を忘れていました。
> > > 追加される = 更新されないなので、 以下のテスト観点の追加により「DBが更新されずに」の部分もテストされていると思っています。
> > > 
> > > * データを与える前にsqlで追加したデータ数分のID列が既に使用されているかの確認テストの追加
> > > * データを与えた後にデータが新規に保存され、追加されているかの確認テストの追加
> > 
> > 
> > 上記テストでは、「更新されない」ことは担保されないですね。（もしかしたら、登録時に他のデータを削除しているかもしれない） なので、追加前のデータがそのまま存在している事を確認する必要があります。

2022-06-21 00:22 UTC, t-ita requested changes
まだ、テストが不足しています。
メソッドの動作結果を確認するためには何が必要かをよく考えましょう。

2022-06-21 00:22 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(maxIdValue, "追加されたデータが存在している");
これだけでは、「何かが追加されている」ことは判断できても、「追加されている何かのデータが正しい」ことは判定できないですよね。データ（またはインスタンス）の比較をするようにしてください。

2022-06-21 00:22 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertTrue(Stream.of(actual.get(0), actual.get(1), actual.get(2), actual.get(3)).anyMatch(s -> s.equals(original.get(2))), "既存のデータが変更されていないか確認");
上で書いていることと同様ですが、ID のチェックだけでは、「データが更新されていない」ことの証左になりません。データ（あるいはインスタンス）を比較してください。

2022-06-21 04:48 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        var maxIdValue = LongStream.of(actual.get(0).getId(), actual.get(1).getId(), actual.get(2).getId(), actual.get(3).getId()).max().getAsLong();
`actual.stream().max(Comparator.comparing(Account::getId)).orElseGet(Assertions::fail)`

上記のコードの意味を以下のように理解したのですが、自分の理解は合っていますでしょうか？

`max(Comparator.comparing(Account::getId))`でComparator Interfaceを使ってAccountインスタンスにあるIDをsortする。
sortした後に、IDの最大値(`max`)に紐付いたインスタンスのデータを取得する。（`orElseGet(Assertions::fail)`は仮に値がな買った場合assertをfailさせるためにある）

2022-06-21 05:25 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        var maxIdValue = LongStream.of(actual.get(0).getId(), actual.get(1).getId(), actual.get(2).getId(), actual.get(3).getId()).max().getAsLong();
@Ryoma137  動作の理解としてはだいたい合ってます。が、私の理解イメージとは異なりますね。
一応私の理解イメージを書いておきますね。

- `stream` は連続した値を(終端処理が要求されたタイミングで)順次処理する
- `max` は引数で渡された比較演算を `stream` の要素に順次適用して最大となる要素を返す `stream` の終端処理
- `max` の結果は `Optional`型になるので、 `orElseGet` で値を取り出す
- 値がない時はテストが実施できない異常な状態であるので、 `Assertions.fail()` を呼ぶようにしている

理解の仕方は人それぞれなのでこの理解が絶対でもありません。いろいろな人の理解や解説を聞いて、誤解がないようにしておきたいですね。(現状は石崎さんの理解でも問題ないと思うので先に進めてください)

2022-06-21 06:52 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        var maxIdValue = LongStream.of(actual.get(0).getId(), actual.get(1).getId(), actual.get(2).getId(), actual.get(3).getId()).max().getAsLong();
指摘部分を修正して再度レビューに出しました。

2022-06-21 06:53 UTC, Ryoma137 commented
不足しているテストを追加しました。

2022-06-21 06:55 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        var maxIdValue = LongStream.of(actual.get(0).getId(), actual.get(1).getId(), actual.get(2).getId(), actual.get(3).getId()).max().getAsLong();
レビューにて確認します。

2022-06-21 06:56 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertTrue(Stream.of(actual.get(0), actual.get(1), actual.get(2), actual.get(3)).anyMatch(s -> s.equals(original.get(2))), "既存のデータが変更されていないか確認");
レビューにて確認します。

2022-06-21 06:56 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(maxIdValue, "追加されたデータが存在している");
レビューにて確認します。

2022-06-21 06:56 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(0), "与えられたデータが存在することの確認");
レビューにて確認します。

2022-06-21 06:56 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(3), "与えられたデータが存在する事を確認");
レビューにて確認します。

2022-06-21 06:56 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertNotNull(actual.get(3).getId(),"データを与えた後にID列の4番目にデータが保存されている事を確認");
レビューにて確認します。

2022-06-21 07:16 UTC, t-ita requested changes
@Ryoma137 あとひといきです。
指摘したので、修正をお願いします。

2022-06-21 07:16 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertEquals(original.stream().map(Account::getItemDate).toList(), recordsWithoutAddedOne.stream().map(Account::getItemDate).collect(Collectors.toList()), "既存データのitemDateの値が変更されていない事を確認");
かなりいい線いってますが、これでは正しく確認できないです。
各フィールドに限定したリストを作って比較していまうと、たとえば

「ID = 1 のレコードの日付と ID=2 のレコードの日付が入れ替わる更新がされた場合」

にテストが通ってしまいます。（日付のリストとしては変わらないので）
ですので、ここは、
```
// actual から追加されたレコードを除いたリストを生成
var actualWithoutAdded = actual.stream().filter(account -> account.getId() != 4).toList();
// 追加されたレコード以外のレコードが、すべて（そのまま）含まれていることを確認
assertTrue(original.contains(actual.get(0)));
assertTrue(original.contains(actual.get(1)));
assertTrue(original.contains(actual.get(2)));
```
のようにすると、レコード毎に存在チェックされるので確実かと思います。
※ 追加前のレコード数は3件なので、ID指定しても問題ありません
※ Account クラスには Lombok の `Data` アノテーションが着いているので、フィールドを比較する同値判定メソッド `equals()` が生成されます
※ `List::contains` は、`equals` メソッドを利用して値が含まれているかどうかをチェックします
※ `Stream::toList()` は `JDK16` からのメソッドなので環境によっては使えないので気を付けてください

2022-06-21 08:38 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        var maxIdValue = actual.stream().max(Comparator.comparing(Account::getId)).orElseGet(Assertions::fail);
変数名を`maxIdValue `から`accountValueWithMaxId`に変更しました。

2022-06-21 08:38 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertEquals(original.stream().map(Account::getItemDate).toList(), recordsWithoutAddedOne.stream().map(Account::getItemDate).collect(Collectors.toList()), "既存データのitemDateの値が変更されていない事を確認");
板垣さんのコメントを参考にテストの修正を行いました。

2022-06-21 08:41 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        var maxIdValue = actual.stream().max(Comparator.comparing(Account::getId)).orElseGet(Assertions::fail);
レビューにて確認します。

2022-06-21 08:41 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertEquals(original.stream().map(Account::getItemDate).toList(), recordsWithoutAddedOne.stream().map(Account::getItemDate).collect(Collectors.toList()), "既存データのitemDateの値が変更されていない事を確認");
レビューにて確認します。

2022-06-21 08:50 UTC, t-ita requested changes
@Ryoma137 私のサンプルコードの意図が伝わっていないようです。

2022-06-21 08:50 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertEquals(3, actual.stream().filter(accountValue -> accountValue.getId() != 4).toList().size(), "追加したデータを除いたデータ数が３である事の確認");
「現在のテーブルレコードのリストから、追加したレコードを除いたリスト」を生成していますが、生成したリストの件数を数えることは無意味です。
私のサンプルコードでは、その後の確認のために必要なリストとして生成しているものなので、そのようにはしていません。

2022-06-21 08:50 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertTrue(original.contains(actual.get(0)), "ID値が1であるデータはデータ追加前にも存在していることの確認");
ここは、私のサンプルコードを読んでもらえるとわかると思うんですが、
「追加したレコードを除いたリストの要素」と比較しなければなりません。
なぜなら、ここで利用している `actual` には追加されたレコードが含まれており、`actual` は順序が保障されていないため、`actual.get(0)` としてしまうと追加されたレコードを取得してしまう可能性があります。

2022-06-21 09:17 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertTrue(original.contains(actual.get(0)), "ID値が1であるデータはデータ追加前にも存在していることの確認");
確かに`actual` のデータを取得しても意味ないですね... `recordsWithoutAddedOne`のデータを取得する様に変更しました。

2022-06-21 09:19 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertEquals(3, actual.stream().filter(accountValue -> accountValue.getId() != 4).toList().size(), "追加したデータを除いたデータ数が３である事の確認");
こちらも確かに生成したリストの件数を数えることは無意味なので、その部分を削除しました。

2022-06-21 09:28 UTC, t-ita approved these changes
@Ryoma137 OKです。JUnit テストが全件成功することを確認し、マージしてください。
ひとつコメントを入れています。今後のテストコード記述の参考にしてください。

2022-06-21 09:28 UTC, t-ita commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertTrue(original.contains(recordsWithoutAddedOne.get(0)), "ID値が1であるデータはデータ追加前にも存在していることの確認");
細かい事ではありますが、index = 0 に格納 Account の「ID値が1である」とは確定出来ないです。たとえ実体がそうであっても、順序が保障されていないので、テストとしては確定出来ないとして扱うほうが正しいです。
なので、ここに書くメッセージとしては、「1件目のデータが追加前と変わらないこと」ぐらいにしておいた方がいいでしょうね。
（直しても直さなくてもいいです）

2022-06-21 10:00 UTC, Ryoma137 commented on src/test/java/com/example/okozukai/repository/AccountRepositoryTest.java
> +        assertTrue(original.contains(recordsWithoutAddedOne.get(0)), "ID値が1であるデータはデータ追加前にも存在していることの確認");
メッセージを修正しました。

2022-06-21 10:00 UTC, merged